stages:
  - mirror
  - sync

mirror:
  stage: mirror
  script:
    - git clone --mirror https://github.com/emadadel4/itt.git /tmp/itt
    - cd /tmp/itt
    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@gitlab.com/emadadel/itt.git
    - git push --mirror origin
  only:
    - triggers

sync_to_codeberg:
  stage: sync
  image: alpine:latest  
  before_script:
    - apk add --no-cache bash git
    - git config --global user.name "emadadel"
  script:
    - git clone --mirror https://gitlab.com/emadadel/itt.git repo
    - cd repo
    - git remote set-url origin https://emadadel:${GITLAB_TOKEN}@codeberg.org/emadadel/itt.git
    - git push --mirror origin
  only:
    - main