name: Build

permissions:
  contents: write
  actions: read

on:
    push:
      branches:
        - main

jobs:
  build-runspace:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PowerShell 7
        uses: actions/setup-pwsh@v2
        with:
          pwsh-version: '7.x'
      
      - name: Run build script with PowerShell 7
        shell: pwsh
        run: |
          $env:TERM = "dumb"
          pwsh -NoProfile -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; ./build.ps1"  
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}