name: Run PowerShell Script

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build.ps1 as Administrator
      shell: pwsh
      run: |
        Start-Process pwsh -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File $PWD/build.ps1' -Verb RunAs
