name: Build Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run build.ps1
      run: |
        Start-Process pwsh -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ./build.ps1' -Verb RunAs
      shell: pwsh

    - name: Configure Git
      run: |
        git config --global user.email "19177373+emadadel4@noreply.github.com"
        git config --global user.name "emadadel4"

    - name: Upload itt.ps1
      run: |
        $scriptPath = './itt.ps1'
        if (Test-Path $scriptPath) {
          git add $scriptPath
          git commit -m "Update itt.ps1" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/emadadel4/ITT.git" main
        } else {
          Write-Host "The file itt.ps1 does not exist."
        }
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
