name: Run PowerShell Script on Commit

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-python@v2

    - name: Run build.ps1 script
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        .\build.ps1
      shell: pwsh
