name: Build Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PowerShell 7
      uses: pwsh/pwsh@v7

    - name: Run build.ps1 as Admin
      run: |
        Start-Process pwsh -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ./build.ps1' -Verb RunAs
      shell: pwsh

    - name: Use GITHUB_TOKEN (if needed)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Using GITHUB_TOKEN for further operations"
