name: Build

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
  push:
    branches:
      - update

jobs:
  build-runspace:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build project
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; ./build.ps1
        continue-on-error: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if releasenotes.md has changes
        id: check_changes
        run: |
          git fetch origin
          git diff --name-only HEAD~1 HEAD | grep 'releasenotes.md' || echo "No changes in releasenotes.md" > /dev/null

      - name: Commit 'itt' file if releasenotes.md has changed
        if: success() && steps.check_changes.outputs.has_changed == 'true'
        run: |
          git config --global user.name "emadadel4"
          git config --global user.email "19177373+emadadel4@users.noreply.github.com"
          git add itt
          git commit -m "update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
