name: Build On Change

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download PowerShell Script
      run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/emadadel4/ITT/main/build.ps1" -OutFile "build.ps1"
      shell: pwsh

    - name: Run PowerShell Script
      run: pwsh ./build.ps1
