name: Run PowerShell Script on Repository Change

on:
  push:
    branches:
      - main  # or specify the branches you want to monitor

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run build script
      shell: pwsh
      run: ./build.ps1
