name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v1

    - name: Run build.ps1
      run: ./build.ps1
      shell: pwsh

    - name: Use GITHUB_TOKEN (if needed)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Using GITHUB_TOKEN for further operations"
