name: Run PowerShell Script as Administrator on Commit

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest  # Runs on the latest version of Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up PowerShell
        # Uses GitHub Actions' built-in PowerShell environment
        shell: pwsh
      
      - name: Execute PowerShell script as Administrator
        shell: pwsh
        run: |
          # Define the path to your script
          $scriptPath = "$env:GITHUB_WORKSPACE\test.ps1"
          
          # Check if the script file exists
          if (Test-Path $scriptPath) {
            # Create a new PowerShell process with elevated privileges
            Start-Process pwsh -ArgumentList "-File $scriptPath" -Verb RunAs -Wait
          } else {
            Write-Error "Script file not found: $scriptPath"
            exit 1
          }
