name: Run PowerShell script on commit

on: [push]

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: powershell
        run: |
          Start-Process powershell.exe -Verb RunAs -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File /test.ps1'
