name: Run PowerShell script on commit

on:
  push:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: pwsh
        run: |
          $scriptPath = "$env:GITHUB_WORKSPACE\test.ps1"
          if (Test-Path $scriptPath) {
            Start-Process -FilePath $scriptPath -Verb RunAs -Wait
          } else {
            Write-Error "Script $scriptPath not found."
            exit 1
          }
