name: Run PowerShell script on commit

on:
  push:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell environment
        uses: microsoft/powershell@v1

      - name: Run PowerShell script
        shell: pwsh
        run: |
          Start-Process -FilePath "$env:GITHUB_WORKSPACE\test.ps1" -Verb RunAs -Wait
