name: Run build script and commit changes

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "emadadel1920@gmail.com"
          git config --global user.name "emadadel"

      - name: Run PowerShell script and commit changes
        shell: powershell
        run: |
          # Run build.ps1 script
          Start-Process powershell.exe -Verb RunAs -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File build.ps1'

          # Stage all changes
          git add .

          # Commit changes with a generic message
          git commit -m "Automated build script execution"

          # Push changes back to the repository
          git push origin main  # Replace 'main' with your branch name
