name: Run PowerShell script on commit

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: pwsh
        run: |
          Start-Process -FilePath "$PSScriptRoot\test.ps1" -Verb RunAs -Wait
