name: Sync to SourceForge

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "emadadel"
          git config --global user.email "19177373+emadadel4@users.noreply.github.com"

      - name: Add SourceForge remote
        run: |
          git remote add sourceforge https://emadadel:${{ secrets.SOURCEFORGE_TOKEN }}@git.code.sf.net/p/itt/code.git

      - name: Push changes to SourceForge
        run: |
          git push --force --set-upstream sourceforge main
