name: Sync to SourceForge

on:
  push:
    branches:
      - main  # Or whatever branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add SourceForge remote
        run: git remote add sourceforge git://git.code.sf.net/p/projectname/code

      - name: Push to SourceForge
        run: git push sourceforge main
